/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package railway;
import java.sql.*;
import net.proteanit.sql.DbUtils;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class TrainInfo extends javax.swing.JFrame {
    Connection myConn = null;
    Statement myStmt = null;
    ResultSet myRs = null;
    PreparedStatement ps = null;
    String user = "root";
    String pass = "root";
    public int tid;
    public int userId;
    public String ss;
    public String dd;
    /**
     * Creates new form TrainInfo
     */
    public TrainInfo(int train_id, int uid, String s, String d) {
        tid=train_id;
        userId=uid;
        ss=s;
        dd=d;
        initComponents();
        try{
            myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/railway", user, pass);
            myStmt = myConn.createStatement();
            System.out.println("Done");
            
            String sql="SELECT * FROM train WHERE train_id= '" + train_id+ "'";
            ps=myConn.prepareStatement(sql);
            myRs=ps.executeQuery();
            ps=myConn.prepareStatement(sql);
            myRs=ps.executeQuery();
            myRs.next();
            tno.setText(myRs.getString("train_id"));
            tname.setText(myRs.getString("train_name"));
            tsrc.setText(myRs.getString("source"));
            tdest.setText(myRs.getString("destination"));
            tseat.setText(myRs.getString("no_of_seats"));
        }catch(Exception ex){
            System.out.println(ex);
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tno = new javax.swing.JLabel();
        book = new javax.swing.JButton();
        back = new javax.swing.JButton();
        tname = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tsrc = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tdest = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tseat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        book.setText("BOOK");
        book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookActionPerformed(evt);
            }
        });

        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jLabel2.setText("TRAIN NO:");

        jLabel3.setText("TRAIN NAME");

        jLabel4.setText("SOURCE");

        jLabel6.setText("DESTINATION");

        jLabel8.setText("NO OF VACANT SEATS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(225, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(book)
                        .addGap(114, 114, 114))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(back)
                        .addGap(33, 33, 33))))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tdest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tsrc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tseat, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tno, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(tname, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tsrc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tdest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addComponent(tseat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(book)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookActionPerformed
        
        Random random=new Random();
        try{
            myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/railway", user, pass);
            myStmt = myConn.createStatement();
            System.out.println("Done");
            int vacant= Integer.parseInt(tseat.getText());
            int pnr=random.nextInt(10000) +236000000;
            int flag=0;
            String sql="Select * from passenger";
            ps=myConn.prepareStatement(sql);
            myRs=ps.executeQuery();
            myRs.next();
            while(myRs.next()) {
                int match=myRs.getInt("pnr");
                if(match==pnr){
                    flag=1;
                    break;
                }
            }
            if(flag==1){
                pnr=random.nextInt(10000) +236000000;
            }
            sql="INSERT INTO passenger (`user_id`, `train_id`, `seat_no`, `pnr`) VALUES (?,?,?,?)";
            ps=myConn.prepareStatement(sql);
            ps.setInt(1, userId);
            ps.setInt(2,tid);
            ps.setInt(3,100-vacant+1);
            ps.setInt(4,pnr);
            ps.executeUpdate();
            vacant=vacant-1;
            sql="UPDATE train SET no_of_seats = '"+vacant+"' WHERE train_id = '"+tid+"'";
            ps=myConn.prepareStatement(sql);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Booked");
            BookedList b= new BookedList(userId);
            dispose();
            b.setVisible(true);
            
        }catch(Exception ex){
            System.out.println(ex);
        }        
    }//GEN-LAST:event_bookActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
       try{
            myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/railway", user, pass);
            myStmt = myConn.createStatement();
         
            int check = userId;
            String sql = "Select * from passenger where user_id='"+check+"'";
            ps=myConn.prepareStatement(sql);
            myRs=ps.executeQuery();
            boolean existing=false;
            while(myRs.next())
            {
                existing=true;
                break;
            }
            if(existing==false)
            {
                 Trains t=new Trains(ss,dd,userId);
                dispose();
                t.setVisible(true);
        
            }
            else
            {
                 BookedList b = new BookedList(check);
                 dispose();
                 b.setVisible(true);
            }
            }
        catch (Exception exc) {
           JOptionPane.showMessageDialog(null, exc);
        } 
                
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrainInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrainInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrainInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrainInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new TrainInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton book;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel tdest;
    private javax.swing.JLabel tname;
    private javax.swing.JLabel tno;
    private javax.swing.JLabel tseat;
    private javax.swing.JLabel tsrc;
    // End of variables declaration//GEN-END:variables
}
