/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package railway;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author admin
 */
public class Trains extends javax.swing.JFrame {

    /**
     * Creates new form Trains
     */
    Connection myConn = null;
    Statement myStmt = null;
    ResultSet myRs = null;
    PreparedStatement ps = null;
    String user = "root";
    String pass = "root";
    public int userId;
    public String ss;
    public String dd;
    public Trains(String s, String d,int uid) {
        userId=uid;
        ss=s;
        dd=d;
        initComponents();
        try{
            myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/railway", user, pass);
            myStmt = myConn.createStatement();
            System.out.println("Done");
            String sql="SELECT * FROM train WHERE source= '" + s+ "' and destination= '" + d+ "'";
            ps=myConn.prepareStatement(sql);
            myRs=ps.executeQuery();
            String[] tableColumnsName = {"Train No","Train Name","Source","Destination"}; 
            DefaultTableModel aModel = (DefaultTableModel) trains.getModel();
            aModel.setColumnIdentifiers(tableColumnsName);
            System.out.println(aModel.getRowCount());
            while(myRs.next()){
                Object[] objects = new Object[4];
                int trainId=myRs.getInt("train_id");
                objects[0]=trainId;
                objects[1]=myRs.getString("train_name");
                objects[2]=myRs.getString("source");
                objects[3]=myRs.getString("destination");
                aModel.addRow(objects);
            }
            trains.setModel(aModel);
        }catch(Exception ex){
            System.out.println(ex);
        }        
    }
    
    
    
//    private void Fill(){
//        try{
//            myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/railway", user, pass);
//            myStmt = myConn.createStatement();
//            System.out.println("Done");
//            String sql="select * from train";
//            ps=myConn.prepareStatement(sql);
//            myRs=ps.executeQuery();
//            trains.setModel(DbUtils.resultSetToTableModel(myRs));
//            
//            
//        }catch(Exception ex){
//            System.out.println(ex);
//        }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        trains = new javax.swing.JTable();
        signout = new javax.swing.JButton();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        trains.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        trains.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trainsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(trains);

        signout.setText("SIGN OUT");
        signout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signoutActionPerformed(evt);
            }
        });

        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(back)
                        .addGap(50, 50, 50)
                        .addComponent(signout)
                        .addGap(42, 42, 42))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signout)
                    .addComponent(back))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signoutActionPerformed
       Main m=new Main();
       dispose();
       m.setVisible(true);
    }//GEN-LAST:event_signoutActionPerformed

    private void trainsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trainsMouseClicked
        try{
            myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/railway", user, pass);
            myStmt = myConn.createStatement();
            System.out.println("Done");
            int index=trains.getSelectedRow();
            TableModel model=trains.getModel();
            int train_id = Integer.parseInt(model.getValueAt(index, 0).toString());
            TrainInfo t= new TrainInfo(train_id,userId,ss,dd);
            dispose();
            t.setVisible(true);
            
        }catch(Exception ex){
            System.out.println(ex);
        }        
    }//GEN-LAST:event_trainsMouseClicked

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        Lookup l=new Lookup(userId);
        dispose();
        l.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trains.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trains.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trains.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trains.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Trains().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton signout;
    private javax.swing.JTable trains;
    // End of variables declaration//GEN-END:variables
}
